const PERMISSIONS  = require("./permission")


const ROLES = {
    USER: [
        PERMISSIONS.SNIPPET_CREATE,
        PERMISSIONS.SNIPPET_UPDATE_OWN,
        PERMISSIONS.SNIPPET_DELETE_OWN,
    ],
    ADMIN: [
        PERMISSIONS.SNIPPET_CREATE,
        PERMISSIONS.SNIPPET_UPDATE_OWN,
        PERMISSIONS.SNIPPET_DELETE_OWN,
        PERMISSIONS.SNIPPET_DELETE_ANY,
        PERMISSIONS.USER_MANAGE,
        PERMISSIONS.DELETE_USER,
        PERMISSIONS.USER_GET_ALL,
    ]
}

module.exports = ROLES